name: Build s390x image

on:
  workflow_call:
    inputs:
      target-arch:
        required: true
        type: string

jobs:
  build:
    runs-on: s390x
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t bbolroc/multi-arch-test:${{ inputs.target-arch }} --build-arg ARCH=${{ inputs.target-arch }} .
          docker push bbolroc/multi-arch-test:${{ inputs.target-arch }}
