name: Kata Containers CI
on:
  push:
    branches:
      - 'priate-runner-test'

jobs:
  kata-containers-ci-on-push:
    uses: ./.github/workflows/ci.yaml
    with:
      commit-hash: ${{ github.event.pull_request.head.sha }}
      pr-number: "9999"
      tag: "hchoi"
      target-branch: "main"
    secrets: inherit
