name: Kata Containers CI
on:
  push:
    branches:
      - 'topic/early-tests-on-next-lts-kernel'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  kata-containers-ci-on-push:
    uses: ./.github/workflows/ci.yaml
    with:
      commit-hash: ${{ github.sha }}
      pr-number: 99999
      tag: hchoi-test
      target-branch: main
    secrets: inherit
