name: HCHOI multi-arch build test
on:
  push:
    branches:
      - payload-s390x

jobs:
  build-amd64:
    uses: ./.github/workflows/build-amd64.yaml
    with:
      target-arch: amd64
    secrets: inherit

  build-s390x:
    uses: ./.github/workflows/build-s390x.yaml
    with:
      target-arch: s390x
    secrets: inherit

  publish:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-s390x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push multi-arch manifest
        run: |
          docker manifest create bbolroc/multi-arch-test:latest --amend bbolroc/multi-arch-test:amd64 --amend bbolroc/multi-arch-test:s390x
          docker manifest push bbolroc/multi-arch-test:latest
